### ISSUE TITLE
Accessory is not responding on Home app

### ISSUE THREAD

**Issue by roeekl** [nitaybz/homebridge-electra-smart#9]
Hi,
I have a problem where after few commands, the accessory stops responding on the home app and homebridge.
Here are the logs that was shown at the moment it stopped respond:
```
[4/19/2023, 5:51:43 PM] [homebridge-electra-smart] Characteristic 'Rotation Speed': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
[4/19/2023, 5:51:43 PM] [homebridge-electra-smart] Error:
    at RotationSpeed.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at RotationSpeed.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2557:18)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[4/19/2023, 5:51:43 PM] [homebridge-electra-smart] Characteristic 'Active': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
[4/19/2023, 5:51:43 PM] [homebridge-electra-smart] Error:
    at Active.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at Active.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2557:18)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[4/19/2023, 5:51:43 PM] [ElectraSmart] Living Room AC -> Setting Fan Rotation Speed: 70%
[4/19/2023, 5:51:43 PM] [ElectraSmart] Living Room AC -> Setting Mode to: FAN
[4/19/2023, 5:51:44 PM] [ElectraSmart] Living Room AC  -> Setting New State:
[4/19/2023, 5:51:44 PM] [ElectraSmart] {
  "TURN_ON_OFF": "ON",
  "SPT": "25",
  "AC_MODE": "FAN",
  "CLEAR_FILT": "OFF",
  "FANSPD": "HIGH",
  "HSWING": "OFF",
  "IDU_PN": "",
  "IFEEL": "OFF",
  "MSGTYPE": "OPER",
  "OP_VAL_ERR": "OK",
  "SHABAT": "OFF",
  "SLEEP": "OFF",
  "TIMER": "OFF",
  "TURBO": "OFF",
  "VSWING": "OFF"
}
[4/19/2023, 5:51:44 PM] [ElectraSmart] Found valid ssid in cache 13b786d6cbd149bcb32e1067d3a38f73
[4/19/2023, 5:51:44 PM] [ElectraSmart] Creating request to Electra API --->
[4/19/2023, 5:51:44 PM] [ElectraSmart] body: {"pvdid":1,"id":99,"cmd":"SEND_COMMAND","sid":"13b786d6cbd149bcb32e1067d3a38f73","data":{"id":166348,"commandJson":"{\"OPER\":{\"TURN_ON_OFF\":\"ON\",\"SPT\":\"25\",\"AC_MODE\":\"FAN\",\"CLEAR_FILT\":\"OFF\",\"FANSPD\":\"HIGH\",\"HSWING\":\"OFF\",\"IDU_PN\":\"\",\"IFEEL\":\"OFF\",\"MSGTYPE\":\"OPER\",\"OP_VAL_ERR\":\"OK\",\"SHABAT\":\"OFF\",\"SLEEP\":\"OFF\",\"TIMER\":\"OFF\",\"TURBO\":\"OFF\",\"VSWING\":\"OFF\"}}"}}
[4/19/2023, 5:51:44 PM] [ElectraSmart] Successful response:
[4/19/2023, 5:51:44 PM] [ElectraSmart] {"res":0,"res_desc":null}
[4/19/2023, 5:51:44 PM] [ElectraSmart] Living Room - Updated 'RotationSpeed' for FanService with NEW VALUE: 70
[4/19/2023, 5:51:44 PM] [homebridge-electra-smart] Characteristic 'Rotation Speed': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
[4/19/2023, 5:51:44 PM] [homebridge-electra-smart] Error:
    at RotationSpeed.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at RotationSpeed.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2557:18)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[4/19/2023, 5:51:44 PM] [ElectraSmart] Living Room AC -> Setting Fan Rotation Speed: 39%
[4/19/2023, 5:51:44 PM] [ElectraSmart] Living Room AC -> Setting Mode to: FAN
[4/19/2023, 5:51:44 PM] [homebridge-electra-smart] This plugin threw an error from the characteristic 'Rotation Speed': Unhandled error thrown inside write handler for characteristic: Can't set empty state. See https://homebridge.io/w/JtMGR for more info.
[4/19/2023, 5:51:44 PM] [homebridge-electra-smart] Error: Can't set empty state
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-electra-smart/homekit/StateManager.js:50:14)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
[4/19/2023, 5:51:44 PM] [ElectraSmart] Living Room AC -> Setting Fan Rotation Speed: 38%
[4/19/2023, 5:51:44 PM] [ElectraSmart] Living Room AC -> Setting Mode to: FAN
[4/19/2023, 5:51:44 PM] [homebridge-electra-smart] This plugin threw an error from the characteristic 'Rotation Speed': Unhandled error thrown inside write handler for characteristic: Can't set empty state. See https://homebridge.io/w/JtMGR for more info.
[4/19/2023, 5:51:44 PM] [homebridge-electra-smart] Error: Can't set empty state
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-electra-smart/homekit/StateManager.js:50:14)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
```
From that moment the only solution is to restart homebridge, and reinstall the accessory.

**Comment by nitaybz** [comment]
v2.1.1 (just published) fixed several null-safety holes in the state path and a batching bug that dropped rapid concurrent characteristic changes. Both could plausibly be the root cause here. Please update and let me know if the issue still happens. If it does, post a debug log (`debug: true` in plugin config) so I can dig further.

Sorry for the long delay on this.
